### ISSUE TITLE
Support for per-message duration

### ISSUE THREAD

**Issue by twwwt** [cgross/angular-notify#11]
Hi

It would be cool if the module would support configuring the duration for a message individually. At the moment one can only set the duration globally for any message. Adding `duration` as an optional property to the `objects` argument of `notify()`, that, if set, overwrites the global duration, seems to be what is needed to enable this.

Thanks

**Comment by snrlx** [comment]
I came across the same issue and therefore forked the repository and added it myself. 

You can find the changes in my pull request to this repositoy: https://github.com/cgross/angular-notify/pull/15

If you need it immediately before my changes get pulled, then simply use my fork: https://github.com/snrlx/angular-notify

If you encounter any problems, please let me know :)

**Comment by mxa055** [comment]
+1
