### ISSUE TITLE
Consider publishing to npm

### ISSUE THREAD

**Issue by tamlyn** [cgross/angular-notify#23]
I tend to use only npm these days and not bother with bower. This is one of the few client side packages I can't install via npm. Publishing is a piece of cake, just run [`npm publish`](https://docs.npmjs.com/getting-started/publishing-npm-packages).

**Comment by tamlyn** [comment]
Sorry, I'm being an idiot: `npm install cgross/angular-notify`

**Comment by Misterdjey** [comment]
It does'nt work for me...

Something changes ?

**Comment by tamlyn** [comment]
No, it should still work. What are you trying to do and how is it not working?

**Comment by Misterdjey** [comment]
Thanks for your reply.

I don't know why but the problem comes from my proxy at work.
When I try `npm install cgross/angular-notify` on my own computer, all is fine.

So, forget my comment :)

Thanks
