### ISSUE TITLE
Display notification(s) at the bottom instead of top

### ISSUE THREAD

**Issue by bl4de** [cgross/angular-notify#27]
Hi there,

Thanks for this very useful Angular module.

Because I needed to modify notifications to be able to display them at the bottom of the page, I've forked and modified its code - maybe someone also will look for the same issue, so I've prepared working version available here:

https://github.com/bl4de/angular-notify/tree/master/at-the-bottom

Maybe I should create 'mixed' version with both options and send you some PR for reviewing? What do you think? Let me know in comment ;)

Regards,

R.

**Comment by cgross** [comment]
Sure.  If you can work support for showing notifications on the bottom that would be nice.  Thanks.

**Comment by germanger** [comment]
Whats the status of this? :)

**Comment by sam2x** [comment]
+1 very interested about this. could you merge this feature please ?

**Comment by bl4de** [comment]
Sorry, hadn't enough time recently, but I'm going to provide this as soon as possible.

**Comment by fforres** [comment]
BTW, in case anyone wants to hack this on their own, in this pull request there is a really fast hack

https://github.com/cgross/angular-notify/pull/33/files

**Comment by marco-gagliardi** [comment]
+1

**Comment by herrherrmann** [comment]
+1
Thanks for the work! Would be awesome to see this in the next version.

**Comment by amgadfahmi** [comment]
@forres why this is not merged into the main branch !

**Comment by fforres** [comment]
@amgadfahmi 
I guess it's because it's a global hack. 
I didn't add position and animation calculations for every and each notification.

Although... we should ask @cgross, the library it's kind of dead nowadays :/
