### ISSUE TITLE
Using deprecated $http callback methods.

### ISSUE THREAD

**Issue by angusjfw** [cgross/angular-notify#72]
The $http custom callback methods `success()` and `error()` have been removed from angular 1.6. https://github.com/angular/angular.js/commit/b54a39e2029005e0572fbd2ac0e8f6a4e5d69014

Currently I get the following error using angular-notify:
```
TypeError: $http.get(...).success is not a function
    at notify (webpack:///./~/angular-notify/dist/angular-notify.js?:39)
```

The standard `then()` and `catch()` methods are compatible with older versions so should be used instead.

This should be a minor change, I will submit a PR.

**Comment by farazcsk** [comment]
+1

**Comment by angusjfw** [comment]
Closed as fixed by https://github.com/cgross/angular-notify/commit/4e6ea9524032797c3edc919d44d55afcffda465d.
